import Link from 'next/link'

const sections = [
  {
    section: 1,
    title: 'Section 1 — Everyday Conversation',
    duration: '~8 minutes',
    description: 'Two speakers in a practical everyday context: booking, appointment, or enquiry.',
    difficulty: 'Easier',
    diffColor: 'bg-emerald-100 text-emerald-700',
    icon: '📞',
  },
  {
    section: 2,
    title: 'Section 2 — Monologue',
    duration: '~8 minutes',
    description: 'A single speaker on an everyday topic: tour guide, announcement, or facility info.',
    difficulty: 'Moderate',
    diffColor: 'bg-sky-100 text-sky-700',
    icon: '📢',
  },
  {
    section: 3,
    title: 'Section 3 — Academic Conversation',
    duration: '~8 minutes',
    description: '2–3 speakers in an academic context: study group, project planning, tutorial.',
    difficulty: 'Harder',
    diffColor: 'bg-amber-100 text-amber-700',
    icon: '🎓',
  },
  {
    section: 4,
    title: 'Section 4 — Academic Lecture',
    duration: '~10 minutes',
    description: 'A university-style lecture on an academic subject with complex vocabulary.',
    difficulty: 'Hardest',
    diffColor: 'bg-red-100 text-red-700',
    icon: '🔬',
  },
]

export default function ListeningHubPage() {
  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Listening Practice</h1>
        <p className="mt-1 text-gray-500">
          Choose a section. Audio is generated by AI and plays once — just like the real exam.
        </p>
      </div>

      <div className="grid gap-4">
        {sections.map(s => (
          <Link
            key={s.section}
            href={`/practice/listening/${s.section}`}
            className="group flex items-start gap-5 bg-white rounded-2xl border border-gray-100 p-6 hover:shadow-md hover:border-gray-200 transition-all"
          >
            <div className="text-3xl mt-0.5">{s.icon}</div>
            <div className="flex-1">
              <div className="flex items-start justify-between gap-4 flex-wrap">
                <div>
                  <h2 className="font-semibold text-gray-900 group-hover:text-emerald-600 transition-colors">
                    {s.title}
                  </h2>
                  <p className="mt-1 text-sm text-gray-500 leading-relaxed max-w-lg">{s.description}</p>
                </div>
                <div className="flex items-center gap-2 flex-shrink-0">
                  <span className="text-xs font-medium px-2.5 py-1 rounded-full bg-gray-100 text-gray-600">
                    {s.duration}
                  </span>
                  <span className={`text-xs font-medium px-2.5 py-1 rounded-full ${s.diffColor}`}>
                    {s.difficulty}
                  </span>
                </div>
              </div>
              <div className="mt-4 flex items-center text-sm font-medium text-emerald-600 gap-1">
                Start section
                <svg className="w-4 h-4 group-hover:translate-x-0.5 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                </svg>
              </div>
            </div>
          </Link>
        ))}
      </div>

      <div className="bg-sky-50 border border-sky-100 rounded-2xl p-5">
        <div className="flex items-start gap-3">
          <span className="text-sky-500 mt-0.5">
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </span>
          <div>
            <p className="text-sm font-medium text-sky-800">10 questions per section</p>
            <p className="text-sm text-sky-700 mt-0.5">
              Each section has 10 auto-marked questions. Choose a level to suit your needs:
            </p>
            <div className="mt-3 grid grid-cols-3 gap-2">
              <div className="bg-white/60 rounded-lg px-3 py-2">
                <p className="text-xs font-semibold text-amber-700">Study</p>
                <p className="text-xs text-sky-700 mt-0.5">Transcript + free replay</p>
              </div>
              <div className="bg-white/60 rounded-lg px-3 py-2">
                <p className="text-xs font-semibold text-sky-700">Practice</p>
                <p className="text-xs text-sky-700 mt-0.5">Audio plays once</p>
              </div>
              <div className="bg-white/60 rounded-lg px-3 py-2">
                <p className="text-xs font-semibold text-emerald-700">Test</p>
                <p className="text-xs text-sky-700 mt-0.5">Full exam simulation</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
